  export const contents = [
    {
      id: 1,
      username: "James Almiron",
      userImg: "/general/images/cartoonDP.jpg",
      connections: 89,
      task: "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Dolore praesentium architecto aspernatur possimus ea, asperiores nostrum illo sint veritatis et eligendi ipsum unde corporis quos atque minus commodi doloremque dignissimos.",
      status: "pending",
      originalStatus: "pending",
      time: "2pm",
      deadline: "12-12-2024",
      imgs: ["general/images/wp.jpg"],
      vid: "",
      likes: 886,
      comment: 334,
      saves: 6743,
    },
    {
      id: 2,
      username: "Kelvin Harris",
      userImg: "/general/images/cartoonDP2.jpg",
      connections: 134,
      task: "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Dolore praesentium architecto aspernatur possimus ea, asperiores nostrum illo sint veritatis et eligendi ipsum unde corporis quos atque minus commodi doloremque dignissimos.",
      status: "late",
      originalStatus: "late",
      time: "just now",
      deadline: "12-12-2024",
      imgs: [],
      vid: "",
      likes: 4,
      comment: 56,
      saves: 98,
    },
    {
      id: 3,
      username: "Franklin",
      userImg: "/general/images/franklin.jpg",
      connections: 34,
      task: "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Dolore praesentium architecto aspernatur possimus ea, asperiores nostrum illo sint veritatis et eligendi ipsum unde corporis quos atque minus commodi doloremque dignissimos.",
      status: "pending",
      originalStatus: "pending",
      time: "9:34pm",
      deadline: "12-12-2024",
      imgs: [
        "general/images/wp.jpg",
        "general/images/wp.jpg",
        "general/images/wp.jpg",
      ],
      vid: "",
      likes: 9895,
      comment: 76,
      saves: 234,
      pub: "public",
    },
    {
      id: 4,
      username: "Jane Doe",
      userImg: "/general/images/cartoonDP3.jpg",
      connections: 898,
      task: "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Dolore praesentium architecto aspernatur possimus ea, asperiores nostrum illo sint veritatis et eligendi ipsum unde corporis quos atque minus commodi doloremque dignissimos.",
      status: "pending",
      originalStatus: "pending",
      time: "9:49pm",
      deadline: "12-12-2024",
      imgs: [],
      vid: "",
      likes: 90,
      comment: 76,
      saves: 877,
    },
    {
      id: 5,
      username: "Peter Hudson",
      userImg: "/general/images/user.jpg",
      connections: 675,
      task: "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Dolore praesentium architecto aspernatur possimus ea, asperiores nostrum illo sint veritatis et eligendi ipsum unde corporis quos atque minus commodi doloremque dignissimos.",
      status: "completed",
      originalStatus: "completed",
      time: "5:23am",
      deadline: "12-12-2024",
      imgs: ["general/images/wp.jpg", "general/images/wp.jpg"],
      vid: "",
      likes: 35,
      comment: 76,
      saves: 897,
    },
  ];